# This file was generated by GoReleaser. DO NOT EDIT.
cask "better-drive" do
  version "1.9.0"

  on_macos do
    on_arm do
      sha256 "f5601a9cb549a757fe95a2eeb35c2e9be3a744ac2223ba7b12eb3de164d27e50"
      url "https://github.com/n24q02m/better-drive/releases/download/v#{version}/better-drive_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "176a56f210ad1844ae9817cca13c82f67fe08054151d56562481a74b50eea3ab"
      url "https://github.com/n24q02m/better-drive/releases/download/v#{version}/better-drive_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b1d79371e26d6cb393a8d14cbfdc1794c22b28f9b7ce210683d477d6917b50db"
      url "https://github.com/n24q02m/better-drive/releases/download/v#{version}/better-drive_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "23f8effce462e0f8c236d72b156efa6c28e625d1afcd1e606f26756cba6cd275"
      url "https://github.com/n24q02m/better-drive/releases/download/v#{version}/better-drive_#{version}_linux_amd64.tar.gz"
    end
  end

  name "better-drive"
  desc "2-way Google Drive sync with .driveignore filter (rclone engine, Windows tray)"
  homepage "https://github.com/n24q02m/better-drive"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "rclone",
    ]

  binary "better-drive"

  # No zap stanza required
end
