# This file was generated by GoReleaser. DO NOT EDIT.
cask "better-drive" do
  version "1.5.1"

  on_macos do
    on_intel do
      sha256 "91b1c4a60572270e7562ed699b532487c3637fa9deca7379c72427f778647aae"
      url "https://github.com/n24q02m/better-drive/releases/download/v#{version}/better-drive_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "022605961f7b39c18c8039edc7e470e9d5972e33f1504493c268dcf60b75ba7a"
      url "https://github.com/n24q02m/better-drive/releases/download/v#{version}/better-drive_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "62477f48a0705b5c0b374940e5c7676f78cb76c850c0b2c47eb047a87d6db55e"
      url "https://github.com/n24q02m/better-drive/releases/download/v#{version}/better-drive_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "03cd22a2e0c73cf0c9b7a9ff0da63bd681ccc47bf63d0f1ca25a2d68d14f7297"
      url "https://github.com/n24q02m/better-drive/releases/download/v#{version}/better-drive_#{version}_linux_arm64.tar.gz"
    end
  end

  name "better-drive"
  desc "2-way Google Drive sync with .driveignore filter (rclone engine, Windows tray)"
  homepage "https://github.com/n24q02m/better-drive"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "rclone",
    ]

  binary "better-drive"

  # No zap stanza required

end
