# This file was generated by GoReleaser. DO NOT EDIT.
cask "better-drive" do
  version "1.6.0"

  on_macos do
    on_intel do
      sha256 "8825a960617f1d88c2ef7a7d7ccdcbd29802a79c1acac457aee636554de35218"
      url "https://github.com/n24q02m/better-drive/releases/download/v#{version}/better-drive_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fd334ff06dd823c3b611f526b0e31c739d84b681e99abffd6dcf38f83ece3f0b"
      url "https://github.com/n24q02m/better-drive/releases/download/v#{version}/better-drive_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9a6d544cded3d8676cc60fd89a53a0c363fb2c81ef5ba434b6279e7b17bc7dfc"
      url "https://github.com/n24q02m/better-drive/releases/download/v#{version}/better-drive_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b0b96ac3c7e1fc0bf2c12d105059daa34f2ce272a73dff9a4e018795933d207c"
      url "https://github.com/n24q02m/better-drive/releases/download/v#{version}/better-drive_#{version}_linux_arm64.tar.gz"
    end
  end

  name "better-drive"
  desc "2-way Google Drive sync with .driveignore filter (rclone engine, Windows tray)"
  homepage "https://github.com/n24q02m/better-drive"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "rclone",
    ]

  binary "better-drive"

  # No zap stanza required

end
