# This file was generated by GoReleaser. DO NOT EDIT.
cask "skret" do
  version "1.17.0"

  on_macos do
    on_intel do
      sha256 "8c9fdb5184c12ed3d47c2a5fc9efe1ab5a44f9363f85508ca90a7646c9bf0fbb"
      url "https://github.com/n24q02m/skret/releases/download/v#{version}/skret_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c6bedd15351c969af8062e3cafa40a9705bb4f55a41c16cd01ba6d7a2f6b106d"
      url "https://github.com/n24q02m/skret/releases/download/v#{version}/skret_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f5bdc13077eb568185a5c88cce8b352abd84c5ff1a868af6140628e88fd8b189"
      url "https://github.com/n24q02m/skret/releases/download/v#{version}/skret_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "34d9934888de9b05ccc7b0d7395c8ca6362e519cd25547cb786e9775a66a6f4f"
      url "https://github.com/n24q02m/skret/releases/download/v#{version}/skret_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skret"
  desc "Cloud-provider secret manager CLI with Doppler/Infisical-grade DX"
  homepage "https://skret.n24q02m.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skret"

  generate_completions_from_executable "skret", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
