# This file was generated by GoReleaser. DO NOT EDIT.
cask "skret" do
  version "1.15.1"

  on_macos do
    on_intel do
      sha256 "ef7a1afe446b7b2e6b4751079b48b2992e1a8e0a30261cae8d40cf9b4f68bcef"
      url "https://github.com/n24q02m/skret/releases/download/v#{version}/skret_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f4c08703aa5886f9499b3890fe5dd534a132b9ffc843ce5bc9775e4a36e6b90a"
      url "https://github.com/n24q02m/skret/releases/download/v#{version}/skret_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "282ade7a8f47d9fac268055e7adaf6ef84f96d6531fc934629ed36439e3f6bda"
      url "https://github.com/n24q02m/skret/releases/download/v#{version}/skret_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "283e0c184102e3fb62c2b61b5c02c789705e438191ec8f257c02d95c357c0088"
      url "https://github.com/n24q02m/skret/releases/download/v#{version}/skret_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skret"
  desc "Cloud-provider secret manager CLI with Doppler/Infisical-grade DX"
  homepage "https://skret.n24q02m.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skret"

  generate_completions_from_executable "skret", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :powershell]

  # No zap stanza required

end
