# This file was generated by GoReleaser. DO NOT EDIT.
cask "skret" do
  version "1.16.0"

  on_macos do
    on_intel do
      sha256 "74998c75d6e5e9214be5e7be2cceaa158abf607eced799aaa939564e38d88eb8"
      url "https://github.com/n24q02m/skret/releases/download/v#{version}/skret_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b7f79fa3051d06a25a0cd13e1ad67981bac3b76d03bb6ed4f705a0adeba0a89"
      url "https://github.com/n24q02m/skret/releases/download/v#{version}/skret_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "39e5365a1ea8c3dd105263b7a73d67786bab64e9727c62397eb83b6fe32060e0"
      url "https://github.com/n24q02m/skret/releases/download/v#{version}/skret_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "39df0fa6f5fff5be1fc5ef09ead3060d61cb10445ed774f0f4834cc4ed8a974f"
      url "https://github.com/n24q02m/skret/releases/download/v#{version}/skret_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skret"
  desc "Cloud-provider secret manager CLI with Doppler/Infisical-grade DX"
  homepage "https://skret.n24q02m.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skret"

  generate_completions_from_executable "skret", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :powershell]

  # No zap stanza required

end
