# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BetterDrive < Formula
  desc "2-way Google Drive sync with .driveignore filter (rclone engine, Windows tray)"
  homepage "https://github.com/n24q02m/better-drive"
  version "1.3.0"
  license "MIT"

  depends_on "rclone"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/n24q02m/better-drive/releases/download/v1.3.0/better-drive_1.3.0_darwin_amd64.tar.gz"
      sha256 "47585522e1786581d6cef8f85219e01533da2da84041ba0a99f5e4f315e50aa4"

      define_method(:install) do
        bin.install "better-drive"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/n24q02m/better-drive/releases/download/v1.3.0/better-drive_1.3.0_darwin_arm64.tar.gz"
      sha256 "f636fa142e651b5a216ca14f496424b3c60dccad21d2e4b32ff64c2bedab83b3"

      define_method(:install) do
        bin.install "better-drive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/n24q02m/better-drive/releases/download/v1.3.0/better-drive_1.3.0_linux_amd64.tar.gz"
      sha256 "d1a1189881851493ba8fda302029fe045f7de0adc438f77148683bb2fe0b34f6"
      define_method(:install) do
        bin.install "better-drive"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/n24q02m/better-drive/releases/download/v1.3.0/better-drive_1.3.0_linux_arm64.tar.gz"
      sha256 "b129d67f60f560d9335b4ce2e1c385ff81ae50d5401bf85a22d73f3a1a36c336"
      define_method(:install) do
        bin.install "better-drive"
      end
    end
  end

  test do
    assert_match "better-drive version", shell_output("#{bin}/better-drive --version")
  end
end
