# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skret < Formula
  desc "Cloud-provider secret manager CLI with Doppler/Infisical-grade DX"
  homepage "https://skret.n24q02m.com"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/n24q02m/skret/releases/download/v1.1.1/skret_1.1.1_darwin_amd64.tar.gz"
      sha256 "b7696980aa3757c9e24118fad6bcfc6f41ddb82a5d67e98c17c41156a11e21bf"

      define_method(:install) do
        bin.install "skret"
        generate_completions_from_executable(bin/"skret", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/n24q02m/skret/releases/download/v1.1.1/skret_1.1.1_darwin_arm64.tar.gz"
      sha256 "02f1d59e9d85a6e6aa790c744c25a0d8cbb3a9f2bbb3ce919f9de055dc0988aa"

      define_method(:install) do
        bin.install "skret"
        generate_completions_from_executable(bin/"skret", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/n24q02m/skret/releases/download/v1.1.1/skret_1.1.1_linux_amd64.tar.gz"
      sha256 "5beee7d8c307ead64a354e4f5525ac745b91d8902da857fb35e2793edf85e5fd"
      define_method(:install) do
        bin.install "skret"
        generate_completions_from_executable(bin/"skret", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/n24q02m/skret/releases/download/v1.1.1/skret_1.1.1_linux_arm64.tar.gz"
      sha256 "8767222e9fe30d26f03eedea10ca794bd9e0fd7705829818e61f38551b652c9e"
      define_method(:install) do
        bin.install "skret"
        generate_completions_from_executable(bin/"skret", "completion")
      end
    end
  end

  test do
    assert_match "skret version", shell_output("#{bin}/skret --version")
  end
end
