# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skret < Formula
  desc "Cloud-provider secret manager CLI with Doppler/Infisical-grade DX"
  homepage "https://skret.n24q02m.com"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/n24q02m/skret/releases/download/v1.2.1/skret_1.2.1_darwin_amd64.tar.gz"
      sha256 "68189d20fc6fa1ef928443ab6cb97c05fc8a1d5f02108378f8046e8eb87eb43c"

      define_method(:install) do
        bin.install "skret"
        generate_completions_from_executable(bin/"skret", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/n24q02m/skret/releases/download/v1.2.1/skret_1.2.1_darwin_arm64.tar.gz"
      sha256 "e1b052992397030e067aabe0c4eb25d0cf29f52f8627d2876651b37e925cdb1d"

      define_method(:install) do
        bin.install "skret"
        generate_completions_from_executable(bin/"skret", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/n24q02m/skret/releases/download/v1.2.1/skret_1.2.1_linux_amd64.tar.gz"
      sha256 "e5e0a44f5197327a0d90487a4c7c38aba1b40fb15f463aaf1e62daa87386df1f"
      define_method(:install) do
        bin.install "skret"
        generate_completions_from_executable(bin/"skret", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/n24q02m/skret/releases/download/v1.2.1/skret_1.2.1_linux_arm64.tar.gz"
      sha256 "64146b5b156c5349e8b01efc19112dd30ad60862a8286c00614d97029d4990a5"
      define_method(:install) do
        bin.install "skret"
        generate_completions_from_executable(bin/"skret", "completion")
      end
    end
  end

  test do
    assert_match "skret version", shell_output("#{bin}/skret --version")
  end
end
